"""Central configuration for detection, tracking, warning, and performance."""

from __future__ import annotations


# Runtime
ENABLE_PERCEPTION = True
YOLO_DEVICE = "cpu"


# Detection models
YOLO_MODEL_SIZE = "n"
YOLO_IMAGE_SIZE = 320
YOLO_MAX_FRAME_WIDTH = 640

PEDESTRIAN_CONF_THRESHOLD = 0.30
PEDESTRIAN_IOU_THRESHOLD = 0.50
VEHICLE_CONF_THRESHOLD = 0.35


# Zebra crossing detection
USE_YOLO_ZEBRA_DETECTOR = True
ZEBRA_MODEL_PATH = "weights/zebra.pt"
ZEBRA_CONF_THRESHOLD = 0.25
ZEBRA_IMAGE_SIZE = 640
ZEBRA_CANNY_THRESHOLDS = (30, 120)
ZEBRA_MIN_AREA = 3000
ZEBRA_MIN_ASPECT = 1.2
ZEBRA_MAX_ASPECT = 15.0
ZEBRA_MEMORY_FRAMES = 30
ZEBRA_SMOOTHING_ALPHA = 0.7
ZEBRA_RENDER_STYLE = "simple"
ZEBRA_REFINEMENT_ENABLE = True
ZEBRA_WHITE_SAT_MAX = 96
ZEBRA_WHITE_VALUE_MIN = 150
ZEBRA_REFINEMENT_MIN_PIXELS = 280
ZEBRA_FAST_DETECT_INTERVAL = 15
ZEBRA_HOLD_MAX_MISS_ATTEMPTS = 6
ZEBRA_OCCLUSION_HOLD_RATIO = 0.22
ZEBRA_UPDATE_MIN_IOU = 0.12
ZEBRA_UPDATE_MIN_AREA_RATIO = 0.45
ZEBRA_UPDATE_MAX_AREA_RATIO = 2.20
SCENE_ZONE_ENABLE = True
SCENE_ZONE_CONFIG_PATH = "scene_zones.json"
SCENE_ZONE_DRAW = True
SCENE_AUTO_APPROACH_SCALE_X = 0.45
SCENE_AUTO_APPROACH_SCALE_Y = 0.70
SCENE_AUTO_CONFLICT_SCALE_X = 0.65
SCENE_AUTO_CONFLICT_SCALE_Y = 1.10
SCENE_AUTO_FOCUS_SCALE_X = 0.95
SCENE_AUTO_FOCUS_SCALE_Y = 1.35
SCENE_FOCUS_TRACKING = True
SCENE_FOCUS_IMAGE_SIZE = 640


# Pipeline scheduling
PERSON_DETECT_INTERVAL = 5
ZEBRA_DETECT_INTERVAL = 90
PREDICTION_INTERVAL = 2
KEEP_ORIGINAL_FRAME = False


# Tracking and trajectory prediction
TRACKER_BACKEND = "bytetrack"

TRACK_MAX_HISTORY = 20
TRACK_MAX_MISSED = 8
TRACK_IOU_THRESHOLD = 0.3
TRACK_HIGH_THRESH = 0.25
TRACK_LOW_THRESH = 0.10
TRACK_NEW_THRESH = 0.25
TRACK_MATCH_THRESH = 0.80
TRACK_BUFFER = 30
TRACK_DRAW_HOLD_MS = 400
TRACK_BOX_KALMAN_Q = 0.03
TRACK_BOX_KALMAN_R = 0.12
TRACK_WH_EMA_ALPHA = 0.75
TRACK_ZONE_ENTER_MARGIN = 8

LSTM_HISTORY_LENGTH = 10
LSTM_PRED_STEPS = 12
PRED_SMOOTH_ENABLE = True
PRED_SMOOTH_WINDOW = 3
PRED_SMOOTH_WEIGHTS = (0.2, 0.6, 0.2)
PRED_DRAW_POINTS = 6
PRED_DRAW_STEP = 2


# Risk evaluation
PEDESTRIAN_SPEED_THRESHOLD = 60.0
RISK_TTC_DANGER = 1.5
RISK_TTC_CAUTION = 3.0
RISK_APPROACH_SPEED_FACTOR = 0.45
RISK_ZEBRA_DWELL_FRAMES = 12


# UI and logging
UI_MAX_LOG_LINES = 160
SHOW_PREDICTION_TRAJECTORY = False
SHOW_PERFORMANCE_OVERLAY = False
DISPLAY_FPS_CAP = 30.0
UI_SUMMARY_UPDATE_HZ = 2.0
